### ISSUE TITLE
pip安装autoBinning后，import出错

### ISSUE THREAD

**Issue by hrdg** [kaiwang0112006/autoBinning#1]
No module named 'autoBinning'

**Comment by hrdg** [comment]
from utils.simpleMethods import *
from utils.trendDiscretization import *
from utils.forwardSplit import *
from utils.backwardSplit import *
from utils.mapa import *

t.fit(sby='woe',num_split=4,init_split=20)  #init_split调小可以用

**Comment by kaiwang0112006** [comment]
> from utils.simpleMethods import *
> from utils.trendDiscretization import *
> from utils.forwardSplit import *
> from utils.backwardSplit import *
> from utils.mapa import *
> 
> t.fit(sby='woe',num_split=4,init_split=20) #init_split调小可以用

init_split是初始切点数，如果给0，将使用最细粒度的切点，即相邻特征的中点

**Comment by kaiwang0112006** [comment]
> No module named 'autoBinning'

看下site-package下是否有auto Binning且安装完整

**Comment by kaiwang0112006** [comment]
本身是纯Python的package，直接clone可以import，close
